feat: annotate node load by node name
gocrane/crane-scheduler pull request #19
Opened 2022-08-19 08:23 UTC by wuxs

2022-08-19 11:16 UTC, imneov commented on pkg/controller/annotator/node.go
>  	value, err := promClient.QueryByNodeIP(key, getNodeInternalIP(node))
Would be better like: 
```
         value, err := promClient.QueryByNodeIP(key, getNodeInternalIP(node))
	if err == nil && len(value) > 0 {
                 return patchNodeAnnotation(kubeClient, node, key, value)
        }
        value, err = promClient.QueryByNodeName(key, getNodeName(node))
	if err == nil && len(value) > 0 {
                 return patchNodeAnnotation(kubeClient, node, key, value)
        }
        return fmt.Errorf("failed to get data %s{%s=%s}: %v", key, node.Name, value, err)
```

2022-08-23 04:10 UTC, autumn0207 commented on pkg/controller/prometheus/prometheus.go
> +	// QueryByNodeIP queries data by node IP.
Change `node IP` to `node Name`

2022-08-23 04:10 UTC, autumn0207 commented on pkg/controller/prometheus/prometheus.go
> +	querySelector = fmt.Sprintf("%s{instance=~\"%s:.+\"} /100", metricName, name)
No fuzzy matching is required for `node Name`, and this part can be removed.

2022-08-25 02:17 UTC, xieydd requested changes
can we fix via the comment from @autumn0207

2022-08-25 03:21 UTC, wuxs commented
> can we fix via the comment from @autumn0207

ok

2022-08-27 07:37 UTC, xieydd approved these changes
/lgtm

2022-08-27 07:37 UTC, xieydd commented
Thanks for your controbution @wuxs

2022-08-27 07:37 UTC, merged